[package]
name = "tempserver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.42.0"
config = "0.15.11"
dotenvy = "0.15.7"
futures = "0.3.31"
lettre = "0.11.17"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
uuid = "1.17.0"
