version: "3.3"

services:
  rust-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://root@cockroach:26257/mydb?sslmode=disable
      - NATS_URL=nats://nats:4222
    env_file:
      - .env
    depends_on:
      - cockroach
      - nats

  email-service:
    build:
      context: ./tempserver
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NATS_URL=nats://nats:4222
    env_file:
      - ./tempserver/.env
    depends_on:
      - nats

  cockroach:
    image: cockroachdb/cockroach:v24.1.0
    command: start-single-node --insecure
    ports:
      - "26257:26257" # SQL
      - "8080:8080" # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  nats:
    image: nats:2.10
    ports:
      - "4222:4222" # client
      - "8222:8222" # monitoring
    command: ["-js"]

volumes:
  cockroach-data:
